version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      # Maps Current project directory '.' to working directory in container
      - ./:/usr/src/app
  
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      # Our Node app will use these to connect
      # to the database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      # Default port for PostgreSQL database
      - "5432:5432"
    volumes:
      - ./db-seed.sql:/docker-entrypoint-initdb.d/db-seed.sql